let tileH;
let tileW;
let tileSpacing;
let tileBorderRadius;
let sw;
let widthDivider;
let heightDivider;
let background_color = "#0f0f25";
let displayBackgroundTiles = true;
let main_timer = 0;
let total_collapse_count = 0;
